services:
  - type: web
    name: quran-voice-persona
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn voice_persona_web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0