services:
  - type: web
    name: quran-voice-persona
    runtime: python
    plan: free
    rootDir: voice_persona
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn voice_persona_web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health