[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  # Environment variables should be set in Netlify dashboard
  # Do not commit sensitive keys here

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
