services:
  - type: web
    name: quran-vector-search-api
    env: python
    repo: https://github.com/safmy/QuranCompare
    branch: main
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: USE_CLOUD_VECTORS
        value: true
      - key: RASHAD_FAISS_URL
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/RashadAllMedia.faiss
      - key: RASHAD_JSON_URL
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/RashadAllMedia.json
      - key: FINAL_TESTAMENT_FAISS_URL
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/FinalTestament.faiss
      - key: FINAL_TESTAMENT_JSON_URL  
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/FinalTestament.json
      - key: QURANTALK_FAISS_URL
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/qurantalk_articles_1744655632.faiss
      - key: QURANTALK_JSON_URL
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/qurantalk_articles_1744655632.json
      - key: NEWSLETTERS_FAISS_URL
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/newsletters_comprehensive.faiss
      - key: NEWSLETTERS_JSON_URL
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/newsletters_comprehensive.json
      - key: VERSES_JSON_URL
        value: https://github.com/safmy/QuranCompare/releases/download/v1.0-vectors/verses_final.json